// <auto-generated />
using System;
using DataModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataModel.Migrations
{
    [DbContext(typeof(MMSDbContext))]
    partial class MMSDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DataModel.Identity.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Picture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("DataModel.Models.Entities.Approve", b =>
                {
                    b.Property<int?>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("approveId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("id"), 1L, 1);

                    b.Property<int>("approvedQuantity")
                        .HasColumnType("int");

                    b.Property<int>("requestId")
                        .HasColumnType("int");

                    b.Property<int>("storeItemId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("requestId");

                    b.HasIndex("storeItemId");

                    b.ToTable("Approves");
                });

            modelBuilder.Entity("DataModel.Models.Entities.Customer", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("customerId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<DateTimeOffset?>("birthDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("birthPlace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("homeNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("hrId")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("occupation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("subCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("timeLimit")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("woreda")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("hrId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            id = 1,
                            birthDate = new DateTimeOffset(new DateTime(2022, 8, 1, 10, 39, 47, 957, DateTimeKind.Unspecified).AddTicks(7652), new TimeSpan(0, 3, 0, 0, 0)),
                            birthPlace = "ብቸና ከተማ",
                            homeNumber = "+251923531946",
                            hrId = 1,
                            name = "የሱፍ",
                            occupation = "ጀማሪ የሶፍትዌር ባለሙያ",
                            phoneNumber = "+251923531946",
                            region = "አማራ",
                            sex = "ወንድ",
                            subCity = "ንፋስ ስልክ ላፍቶ",
                            timeLimit = new DateTimeOffset(new DateTime(2022, 8, 1, 10, 39, 47, 957, DateTimeKind.Unspecified).AddTicks(7667), new TimeSpan(0, 3, 0, 0, 0)),
                            woreda = "02"
                        },
                        new
                        {
                            id = 2,
                            birthDate = new DateTimeOffset(new DateTime(2022, 8, 1, 10, 39, 47, 957, DateTimeKind.Unspecified).AddTicks(7670), new TimeSpan(0, 3, 0, 0, 0)),
                            birthPlace = "ባቲ ከተማ",
                            homeNumber = "+251923531946",
                            hrId = 1,
                            name = "ሙሀመድ",
                            occupation = "ጀማሪ የሶፍትዌር ባለሙያ",
                            phoneNumber = "+251923531946",
                            region = "አማራ",
                            sex = "ወንድ",
                            subCity = "ቦሌ",
                            timeLimit = new DateTimeOffset(new DateTime(2022, 8, 1, 10, 39, 47, 957, DateTimeKind.Unspecified).AddTicks(7670), new TimeSpan(0, 3, 0, 0, 0)),
                            woreda = "02"
                        },
                        new
                        {
                            id = 3,
                            birthDate = new DateTimeOffset(new DateTime(2022, 8, 1, 10, 39, 47, 957, DateTimeKind.Unspecified).AddTicks(7672), new TimeSpan(0, 3, 0, 0, 0)),
                            birthPlace = "ጊንጪ ከተማ",
                            homeNumber = "+251923531946",
                            hrId = 2,
                            name = "ሁንዴ",
                            occupation = "ጀማሪ የሶፍትዌር ባለሙያ",
                            phoneNumber = "+251923531946",
                            region = "ኦሮሚያ",
                            sex = "ወንድ",
                            subCity = "ንፋስ ስልክ ላፍቶ",
                            timeLimit = new DateTimeOffset(new DateTime(2022, 8, 1, 10, 39, 47, 957, DateTimeKind.Unspecified).AddTicks(7672), new TimeSpan(0, 3, 0, 0, 0)),
                            woreda = "02"
                        },
                        new
                        {
                            id = 4,
                            birthDate = new DateTimeOffset(new DateTime(2022, 8, 1, 10, 39, 47, 957, DateTimeKind.Unspecified).AddTicks(7674), new TimeSpan(0, 3, 0, 0, 0)),
                            birthPlace = "ብቸና ከተማ",
                            homeNumber = "+251923531946",
                            hrId = 1,
                            name = "ሰማይነህ",
                            occupation = "ጀማሪ የሶፍትዌር ባለሙያ",
                            phoneNumber = "+251923531946",
                            region = "አማራ",
                            sex = "ወንድ",
                            subCity = "ንፋስ ስልክ ላፍቶ",
                            timeLimit = new DateTimeOffset(new DateTime(2022, 8, 1, 10, 39, 47, 957, DateTimeKind.Unspecified).AddTicks(7674), new TimeSpan(0, 3, 0, 0, 0)),
                            woreda = "02"
                        },
                        new
                        {
                            id = 5,
                            birthDate = new DateTimeOffset(new DateTime(2022, 8, 1, 10, 39, 47, 957, DateTimeKind.Unspecified).AddTicks(7676), new TimeSpan(0, 3, 0, 0, 0)),
                            birthPlace = "ብቸና ከተማ",
                            homeNumber = "+251923531946",
                            hrId = 1,
                            name = "የሱፍ",
                            occupation = "ጀማሪ የሶፍትዌር ባለሙያ",
                            phoneNumber = "+251923531946",
                            region = "አማራ",
                            sex = "ወንድ",
                            subCity = "ንፋስ ስልክ ላፍቶ",
                            timeLimit = new DateTimeOffset(new DateTime(2022, 8, 1, 10, 39, 47, 957, DateTimeKind.Unspecified).AddTicks(7676), new TimeSpan(0, 3, 0, 0, 0)),
                            woreda = "02"
                        });
                });

            modelBuilder.Entity("DataModel.Models.Entities.CustomerWarranty", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("warrantyId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int>("customerId")
                        .HasColumnType("int");

                    b.Property<string>("warantiyAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("warantiyRegion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("warantiySubCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("warantiyWoreda")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("warantiyname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("customerId");

                    b.ToTable("CustemerWarranties");

                    b.HasData(
                        new
                        {
                            id = 1,
                            customerId = 1,
                            warantiyAddress = "ብቸና ከተማ",
                            warantiyRegion = "አማራ",
                            warantiySubCity = "ንፋስ ስልክ ላፍቶ",
                            warantiyWoreda = "02",
                            warantiyname = "የሱፍ"
                        },
                        new
                        {
                            id = 2,
                            customerId = 1,
                            warantiyAddress = "ባቲ ከተማ",
                            warantiyRegion = "አማራ",
                            warantiySubCity = "ቦሌ",
                            warantiyWoreda = "02",
                            warantiyname = "ሙሀመድ"
                        },
                        new
                        {
                            id = 3,
                            customerId = 1,
                            warantiyAddress = "ጊንጪ ከተማ",
                            warantiyRegion = "ኦሮሚያ",
                            warantiySubCity = "ንፋስ ስልክ ላፍቶ",
                            warantiyWoreda = "02",
                            warantiyname = "ሁንዴ"
                        },
                        new
                        {
                            id = 4,
                            customerId = 1,
                            warantiyAddress = "ብቸና ከተማ",
                            warantiyRegion = "አማራ",
                            warantiySubCity = "ንፋስ ስልክ ላፍቶ",
                            warantiyWoreda = "02",
                            warantiyname = "ሰማይነህ"
                        });
                });

            modelBuilder.Entity("DataModel.Models.Entities.Distribute", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("distributeId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int>("approveId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("approveId");

                    b.ToTable("Distributes");
                });

            modelBuilder.Entity("DataModel.Models.Entities.HR", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("hrId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("birthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fpId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("higherDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("middleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("occpation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rank")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("reponsibilty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Hrs");

                    b.HasData(
                        new
                        {
                            id = 1,
                            LastName = "አለሙ",
                            birthDate = new DateTime(2022, 8, 1, 10, 39, 47, 957, DateTimeKind.Local).AddTicks(7582),
                            firstName = "የሱፍ",
                            fpId = "26505157",
                            gender = "ወንድ",
                            higherDate = new DateTime(2022, 8, 1, 10, 39, 47, 957, DateTimeKind.Local).AddTicks(7591),
                            middleName = "ፈንታ",
                            occpation = "ጀማሪ የሶፍትዌር ባለሙያ",
                            rank = "J_V / ጀማሪ",
                            reponsibilty = "የሲቪል ሰራተኛ"
                        },
                        new
                        {
                            id = 2,
                            LastName = "አሊ",
                            birthDate = new DateTime(2022, 8, 1, 10, 39, 47, 957, DateTimeKind.Local).AddTicks(7593),
                            firstName = "ሙሀመድ",
                            fpId = "26505152",
                            gender = "ወንድ",
                            higherDate = new DateTime(2022, 8, 1, 10, 39, 47, 957, DateTimeKind.Local).AddTicks(7593),
                            middleName = "ሁሴን",
                            occpation = "ጀማሪ የሶፍትዌር ባለሙያ",
                            rank = "J_V / ጀማሪ",
                            reponsibilty = "የሲቪል ሰራተኛ"
                        },
                        new
                        {
                            id = 3,
                            LastName = "ኦርጌሳ",
                            birthDate = new DateTime(2022, 8, 1, 10, 39, 47, 957, DateTimeKind.Local).AddTicks(7594),
                            firstName = "ሁንዴ",
                            fpId = "26505156",
                            gender = "ወንድ",
                            higherDate = new DateTime(2022, 8, 1, 10, 39, 47, 957, DateTimeKind.Local).AddTicks(7594),
                            middleName = "ረጋሳ",
                            occpation = "ጀማሪ የሶፍትዌር ባለሙያ",
                            rank = "J_V / ጀማሪ",
                            reponsibilty = "የሲቪል ሰራተኛ"
                        },
                        new
                        {
                            id = 4,
                            LastName = "ታደሰ",
                            birthDate = new DateTime(2022, 8, 1, 10, 39, 47, 957, DateTimeKind.Local).AddTicks(7595),
                            firstName = "ሰማይነህ",
                            fpId = "26505155",
                            gender = "ወንድ",
                            higherDate = new DateTime(2022, 8, 1, 10, 39, 47, 957, DateTimeKind.Local).AddTicks(7596),
                            middleName = "ከበደ",
                            occpation = "ጀማሪ የዌብሳይት አስተዳደር ባለሙያ",
                            rank = "J_V / ጀማሪ",
                            reponsibilty = "የሲቪል ሰራተኛ"
                        },
                        new
                        {
                            id = 5,
                            LastName = "ተንኮሉ",
                            birthDate = new DateTime(2022, 8, 1, 10, 39, 47, 957, DateTimeKind.Local).AddTicks(7596),
                            firstName = "ተረፈ",
                            fpId = "fp2650",
                            gender = "ወንድ",
                            higherDate = new DateTime(2022, 8, 1, 10, 39, 47, 957, DateTimeKind.Local).AddTicks(7597),
                            middleName = "በከለ",
                            occpation = "ዋና ክፍል ሀላፊ",
                            rank = "ዋና ክፍል",
                            reponsibilty = "ዋና ክፍል"
                        });
                });

            modelBuilder.Entity("DataModel.Models.Entities.NotifyHeader", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("notifyHeaderId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("attachments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("itemDescription")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("id");

                    b.ToTable("NotifyHeaders");

                    b.HasData(
                        new
                        {
                            id = 1,
                            attachments = "Upload your Attachment",
                            itemDescription = "የኢትዮጵያ መከላከያ መሳሪያዎችና ጥይቶች"
                        },
                        new
                        {
                            id = 2,
                            attachments = "Upload your Attachment",
                            itemDescription = "የፌደራል ፖሊስ የክላሽ ጠብመንጃዎችና ጥይች"
                        });
                });

            modelBuilder.Entity("DataModel.Models.Entities.NotifyItem", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("notifyItemId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("model")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("notifyHeaderId")
                        .HasColumnType("int");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("id");

                    b.HasIndex("notifyHeaderId");

                    b.ToTable("NotifyItems");

                    b.HasData(
                        new
                        {
                            id = 1,
                            model = "ክላሽ ጠብመንጃ",
                            name = "ክላሽ ጠብመንጃ",
                            notifyHeaderId = 1,
                            quantity = 10,
                            type = "ክላሽ ጠብመንጃ"
                        },
                        new
                        {
                            id = 2,
                            model = "ክላሽ ጠብመንጃ ካርታ",
                            name = "ክላሽ ጠብመንጃ ካርታ",
                            notifyHeaderId = 2,
                            quantity = 10,
                            type = "ክላሽ ጠብመንጃ ካርታ"
                        },
                        new
                        {
                            id = 3,
                            model = "የፒኬአም መተረየስ",
                            name = "የፒኬአም መተረየስ",
                            notifyHeaderId = 1,
                            quantity = 10,
                            type = "የፒኬአም መተረየስ"
                        },
                        new
                        {
                            id = 4,
                            model = "ካኑኒ ኤስ ሽጉጥ",
                            name = "ካኑኒ ኤስ ሽጉጥ",
                            notifyHeaderId = 2,
                            quantity = 10,
                            type = "ካኑኒ ኤስ ሽጉጥ"
                        },
                        new
                        {
                            id = 5,
                            model = "ጠብመንጃ AK-47",
                            name = "ክላሽ ጠብመንጃ AK-47",
                            notifyHeaderId = 2,
                            quantity = 10,
                            type = "ክላሽ ጠብመንጃ"
                        });
                });

            modelBuilder.Entity("DataModel.Models.Entities.RequestHeader", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("requestHeaderId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("attachments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("hrId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("hrId");

                    b.ToTable("RequestHeaders");

                    b.HasData(
                        new
                        {
                            id = 1,
                            attachments = "Upload your Attachment",
                            description = "የኢትዮጵያ መከላከያ መሳሪያዎችና ጥይቶች",
                            hrId = 1
                        },
                        new
                        {
                            id = 2,
                            attachments = "Upload your Attachment",
                            description = "የፌደራል ፖሊስ የክላሽ ጠብመንጃዎችና ጥይች",
                            hrId = 2
                        });
                });

            modelBuilder.Entity("DataModel.Models.Entities.RequestItem", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("requestItemId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int>("approvedQuantity")
                        .HasColumnType("int");

                    b.Property<string>("attachments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("requestHeaderId")
                        .HasColumnType("int");

                    b.Property<int>("requestedQuantity")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("requestHeaderId");

                    b.ToTable("RequestItems");

                    b.HasData(
                        new
                        {
                            id = 1,
                            approvedQuantity = 0,
                            attachments = "Upload your Attachment",
                            model = "ክላሽ ጠብመንጃ",
                            name = "የኢትዮጵያ መከላከያ መሳሪያዎችና ጥይቶች",
                            requestHeaderId = 1,
                            requestedQuantity = 10,
                            status = "Pending",
                            type = "ክላሽ ጠብመንጃ"
                        },
                        new
                        {
                            id = 2,
                            approvedQuantity = 0,
                            attachments = "Upload your Attachment",
                            model = "ክላሽ ጠብመንጃ ካርታ",
                            name = "የኢትዮጵያ መከላከያ መሳሪያዎችና ጥይቶች",
                            requestHeaderId = 1,
                            requestedQuantity = 5,
                            status = "Pending",
                            type = "ክላሽ ጠብመንጃ ካርታ"
                        },
                        new
                        {
                            id = 3,
                            approvedQuantity = 0,
                            attachments = "Upload your Attachment",
                            model = "የፒኬአም መተረየስ",
                            name = "የፌደራል ፖሊስ የክላሽ ጠብመንጃዎችና ጥይች",
                            requestHeaderId = 1,
                            requestedQuantity = 10,
                            status = "Pending",
                            type = "የፒኬአም መተረየስ"
                        },
                        new
                        {
                            id = 4,
                            approvedQuantity = 0,
                            attachments = "Upload your Attachment",
                            model = "ክላሽ ጠብመንጃ AK-47",
                            name = "የኢትዮጵያ መከላከያ መሳሪያዎችና ጥይቶች",
                            requestHeaderId = 2,
                            requestedQuantity = 10,
                            status = "Pending",
                            type = "ክላሽ ጠብመንጃ"
                        },
                        new
                        {
                            id = 5,
                            approvedQuantity = 0,
                            attachments = "Upload your Attachment",
                            model = "ካኑኒ ኤስ ሽጉጥ",
                            name = "የፌደራል ፖሊስ የክላሽ ጠብመንጃዎችና ጥይች",
                            requestHeaderId = 2,
                            requestedQuantity = 10,
                            status = "Pending",
                            type = "ካኑኒ ኤስ ሽጉጥ"
                        },
                        new
                        {
                            id = 6,
                            approvedQuantity = 0,
                            attachments = "Upload your Attachment",
                            model = "ካኑኒ ኤስ ሽጉጥ",
                            name = "የፌደራል ፖሊስ የክላሽ ጠብመንጃዎችና ጥይች",
                            requestHeaderId = 2,
                            requestedQuantity = 5,
                            status = "Pending",
                            type = "ካኑኒ ኤስ ሽጉጥ"
                        });
                });

            modelBuilder.Entity("DataModel.Models.Entities.ReturnHeader", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("returnHeaderId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("attachments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("hrId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("hrId");

                    b.ToTable("ReturnHeaders");
                });

            modelBuilder.Entity("DataModel.Models.Entities.ReturnItem", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("returnItemId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("returnHeaderId")
                        .HasColumnType("int");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("returnHeaderId");

                    b.ToTable("ReturnItems");
                });

            modelBuilder.Entity("DataModel.Models.Entities.StoreHeader", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("storeHeaderId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("donor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("itemNoInExpenditureRegister")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noOfEntryInTheRegisterOfIncomingGoods")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("notifyHeaderId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("StoreHeaders");

                    b.HasData(
                        new
                        {
                            id = 1,
                            donor = "የኢትዮጵያ መከላከያ",
                            itemNoInExpenditureRegister = "no. 1",
                            noOfEntryInTheRegisterOfIncomingGoods = "10 items",
                            notifyHeaderId = 0
                        },
                        new
                        {
                            id = 2,
                            donor = "የኢትዮጵያ መከላከያ",
                            itemNoInExpenditureRegister = "no. 2",
                            noOfEntryInTheRegisterOfIncomingGoods = "10 items",
                            notifyHeaderId = 0
                        });
                });

            modelBuilder.Entity("DataModel.Models.Entities.StoreItem", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("storeItemId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<bool>("availability")
                        .HasColumnType("bit");

                    b.Property<int>("availableQuantity")
                        .HasColumnType("int");

                    b.Property<string>("itemDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.Property<string>("serialNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("shelfNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("storeHeaderId")
                        .HasColumnType("int");

                    b.Property<string>("storeNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("storeHeaderId");

                    b.ToTable("StoreItems");

                    b.HasData(
                        new
                        {
                            id = 1,
                            availability = true,
                            availableQuantity = 10,
                            itemDescription = "የኢትዮጵያ መከላከያ መሳሪያዎችና ጥይቶች",
                            model = "ክላሽ ጠብመንጃ",
                            quantity = 10,
                            serialNo = "serial 1",
                            shelfNo = "No. 1",
                            storeHeaderId = 1,
                            storeNo = "No. 1",
                            type = "ክላሽ ጠብመንጃ"
                        },
                        new
                        {
                            id = 2,
                            availability = true,
                            availableQuantity = 10,
                            itemDescription = "የኢትዮጵያ መከላከያ መሳሪያዎችና ጥይቶች",
                            model = "ክላሽ ጠብመንጃ ካርታ",
                            quantity = 10,
                            serialNo = "serial 2",
                            shelfNo = "No 2",
                            storeHeaderId = 1,
                            storeNo = "No. 1",
                            type = "ክላሽ ጠብመንጃ ካርታ"
                        },
                        new
                        {
                            id = 3,
                            availability = true,
                            availableQuantity = 10,
                            itemDescription = "የፌደራል ፖሊስ የክላሽ ጠብመንጃዎችና ጥይች",
                            model = "የፒኬአም መተረየስ",
                            quantity = 10,
                            serialNo = "serial 3",
                            shelfNo = "No. 1",
                            storeHeaderId = 2,
                            storeNo = "N0 2",
                            type = "የፒኬአም መተረየስ"
                        },
                        new
                        {
                            id = 4,
                            availability = true,
                            availableQuantity = 10,
                            itemDescription = "የኢትዮጵያ መከላከያ መሳሪያዎችና ጥይቶች",
                            model = "ክላሽ ጠብመንጃ AK-47",
                            quantity = 10,
                            serialNo = "serial 4",
                            shelfNo = "No 2",
                            storeHeaderId = 1,
                            storeNo = "No. 1",
                            type = "ክላሽ ጠብመንጃ"
                        },
                        new
                        {
                            id = 5,
                            availability = true,
                            availableQuantity = 10,
                            itemDescription = "የፌደራል ፖሊስ የክላሽ ጠብመንጃዎችና ጥይች",
                            model = "ካኑኒ ኤስ ሽጉጥ",
                            quantity = 10,
                            serialNo = "serial 5",
                            shelfNo = "No. 1",
                            storeHeaderId = 2,
                            storeNo = "N0 2",
                            type = "ካኑኒ ኤስ ሽጉጥ"
                        },
                        new
                        {
                            id = 6,
                            availability = true,
                            availableQuantity = 10,
                            itemDescription = "የፌደራል ፖሊስ የክላሽ ጠብመንጃዎችና ጥይች",
                            model = "ካኑኒ ኤስ ሽጉጥ",
                            quantity = 10,
                            serialNo = "serial 6",
                            shelfNo = "No. 1",
                            storeHeaderId = 1,
                            storeNo = "N0 2",
                            type = "ካኑኒ ኤስ ሽጉጥ"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "3fc8cda0-d45c-4949-b7b4-081b9cc21d8b",
                            ConcurrencyStamp = "895ad922-498e-4f70-b10a-9f4be6c73b14",
                            Name = "mmd",
                            NormalizedName = "MMD"
                        },
                        new
                        {
                            Id = "33fcc74d-265a-4faa-a0c9-e76cb6abd580",
                            ConcurrencyStamp = "d69a8986-163e-486d-a17d-480acc7d035c",
                            Name = "Admin",
                            NormalizedName = "Admin"
                        },
                        new
                        {
                            Id = "9983c6cd-45e3-4141-8c2a-90a8e1637a7a",
                            ConcurrencyStamp = "0a4be211-9047-458a-b5cc-3028e8c37334",
                            Name = "storeman",
                            NormalizedName = "storeman"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UsersTokens", (string)null);
                });

            modelBuilder.Entity("DataModel.Models.Entities.Approve", b =>
                {
                    b.HasOne("DataModel.Models.Entities.RequestItem", "RequestItem")
                        .WithMany()
                        .HasForeignKey("requestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataModel.Models.Entities.StoreItem", "StoreItem")
                        .WithMany()
                        .HasForeignKey("storeItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RequestItem");

                    b.Navigation("StoreItem");
                });

            modelBuilder.Entity("DataModel.Models.Entities.Customer", b =>
                {
                    b.HasOne("DataModel.Models.Entities.HR", "HR")
                        .WithMany()
                        .HasForeignKey("hrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HR");
                });

            modelBuilder.Entity("DataModel.Models.Entities.CustomerWarranty", b =>
                {
                    b.HasOne("DataModel.Models.Entities.Customer", "Customer")
                        .WithMany("CustomerWarranties")
                        .HasForeignKey("customerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("DataModel.Models.Entities.Distribute", b =>
                {
                    b.HasOne("DataModel.Models.Entities.Approve", "Approve")
                        .WithMany()
                        .HasForeignKey("approveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Approve");
                });

            modelBuilder.Entity("DataModel.Models.Entities.NotifyItem", b =>
                {
                    b.HasOne("DataModel.Models.Entities.NotifyHeader", "NotifyHeader")
                        .WithMany("NotifyItems")
                        .HasForeignKey("notifyHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NotifyHeader");
                });

            modelBuilder.Entity("DataModel.Models.Entities.RequestHeader", b =>
                {
                    b.HasOne("DataModel.Models.Entities.HR", "HR")
                        .WithMany()
                        .HasForeignKey("hrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HR");
                });

            modelBuilder.Entity("DataModel.Models.Entities.RequestItem", b =>
                {
                    b.HasOne("DataModel.Models.Entities.RequestHeader", "RequestHeader")
                        .WithMany("RequestItems")
                        .HasForeignKey("requestHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RequestHeader");
                });

            modelBuilder.Entity("DataModel.Models.Entities.ReturnHeader", b =>
                {
                    b.HasOne("DataModel.Models.Entities.HR", "HR")
                        .WithMany()
                        .HasForeignKey("hrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HR");
                });

            modelBuilder.Entity("DataModel.Models.Entities.ReturnItem", b =>
                {
                    b.HasOne("DataModel.Models.Entities.ReturnHeader", "ReturnHeader")
                        .WithMany("ReturnItems")
                        .HasForeignKey("returnHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReturnHeader");
                });

            modelBuilder.Entity("DataModel.Models.Entities.StoreItem", b =>
                {
                    b.HasOne("DataModel.Models.Entities.StoreHeader", "StoreHeader")
                        .WithMany("StoreItems")
                        .HasForeignKey("storeHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StoreHeader");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DataModel.Identity.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DataModel.Identity.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataModel.Identity.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DataModel.Identity.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataModel.Models.Entities.Customer", b =>
                {
                    b.Navigation("CustomerWarranties");
                });

            modelBuilder.Entity("DataModel.Models.Entities.NotifyHeader", b =>
                {
                    b.Navigation("NotifyItems");
                });

            modelBuilder.Entity("DataModel.Models.Entities.RequestHeader", b =>
                {
                    b.Navigation("RequestItems");
                });

            modelBuilder.Entity("DataModel.Models.Entities.ReturnHeader", b =>
                {
                    b.Navigation("ReturnItems");
                });

            modelBuilder.Entity("DataModel.Models.Entities.StoreHeader", b =>
                {
                    b.Navigation("StoreItems");
                });
#pragma warning restore 612, 618
        }
    }
}
